export type Technology =
    | "Astro"
    | "Tailwind CSS"
    | "Svelte"
    | "JavaScript"
    | "Typescript"
    | "Rust"
    | "Go Lang"
    | "Python"
    | "Netlify"
    | "Deno"
    | "Jamstack"
    | "Strapi CMS"
    | "PostgreSQL"
    | "Mongo DB"
    | "Kali Linux"
    | "Ubuntu Linux"
    | "Raspberry Pi"
    | "React"
    | "Eleventy"
    | "Next JS"
    | "Microsoft"
    | "Excel"
